dist: focal   
language: node_js
node_js:
  - "19.9.0"

before_install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  - nvm install 19.9.0
  - node -v
  - npm -v
  
cache:
  directories:
    - ~/.npm

install:
  - npm install

script:
  - npm run build 
  - npm start &   
  - sleep 15      

on:
push:
  branches:
    - main


# env:
#   global:
#     - NEXT_PUBLIC_CMS_URL=<URL do CMS>
#     - NEXT_PUBLIC_API_URL=<URL da API>

