dist: focal   # Use a distribuição Ubuntu 20.04 LTS
language: node_js
node_js:
  - "19.9.0"

before_install:
  - nvm install 19.9.0
  
cache:
  directories:
    - ~/.npm

install:
  - npm install

script:
  - npm run build # Build your Next.js project
  - npm start &   # Start your Next.js server in the background
  - sleep 15      # Wait for the server to start

on:
push:
  branches:
    - main


# env:
#   global:
#     - NEXT_PUBLIC_CMS_URL=<URL do CMS>
#     - NEXT_PUBLIC_API_URL=<URL da API>

# Variáveis de ambiente sensíveis podem ser configuradas no painel do Travis CI.
